version: "3.4"

services:
  eszop-api-gateway:
    image: eszop-api-gateway
    container_name: eszop-api-gateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "10000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${CERT_PATH}:/https/
    networks:
      - eszop-network

  eszop-offers:
    image: eszop-offers
    container_name: eszop-offers
    build:
      context: .
      dockerfile: Offers.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    networks:
      - eszop-network

  eszop-identity:
    image: eszop-identity
    container_name: eszop-identity
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6000:80"
    networks:
      - eszop-network

  eszop-carts:
    image: eszop-carts
    container_name: eszop-carts
    build:
      context: .
      dockerfile: Carts.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7000:80"
    networks:
      - eszop-network

  eszop-orders:
    image: eszop-orders
    container_name: eszop-orders
    build:
      context: .
      dockerfile: Orders.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    networks:
      - eszop-network

networks:
  eszop-network:
    external:
      name: eszop-network
