SQLSERVER_USERNAME: [FILL ME]
SQLSERVER_PASSWORD: [FILL ME]
REDIS_ADDRESS: [FILL ME]
REDIS_PORT: [FILL ME]
REDIS_PASSWORD: [FILL ME]
ESZOP_AZURE_STORAGE_CONN_STR: [FILL ME]
ESZOP_AZURE_EVENTBUS_CONN_STR: [FILL ME]
ESZOP_SQLSERVER_CONN_STR_TEMPLATE: [FILL ME]